const lang = {
  en: {
    fullTitle: "English",
    gptSerchPlaceholder: "What would you like to watch today?",
    searchButton: "Search",
    apiParam: "en-US",
    playButton: "Play",
    moreInfoButton: "More Info",
    signOutText: "Sign Out",
    nowPlaying: "Now Playing",
    upcoming: "Upcoming",
    topRated: "Top Rated",
    popular: "Popular",
    gptSearch: "GPT Search",
    signIn: "Sign In",
    signUp: "Sign Up",
    newToNetflix: "New to Netflix?",
    alreadyRegistered: "Already registered?",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    suggestedMovies: "Suggested Movies",
    searching: "Searching...",
    goBack: "Go Back",
  },
  hi: {
    fullTitle: "हिंदी",
    gptSerchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    searchButton: "खोजें",
    apiParam: "hi-IN",
    playButton: "चलाएँ",
    moreInfoButton: "और जानकारी",
    signOutText: "बाहर जाएं",
    nowPlaying: "अभी चल रहीं",
    upcoming: "आगामी",
    topRated: "शीर्ष रेटेड",
    popular: "लोकप्रिय",
    gptSearch: "जीपीटी खोज",
    signIn: "दाखिल करें",
    signUp: "साइन अप करें",
    newToNetflix: "नेटफ्लिक्स पर नए हैं?",
    alreadyRegistered: "पहले से पंजीकृत?",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "कुंजिका",
    suggestedMovies: "सुझाई गई फिल्में",
    searching: "तलाश की जा रही है ...",
    goBack: "वापस जाओ",
  },
  es: {
    fullTitle: "Español",
    gptSerchPlaceholder: "¿Qué te gustaría ver hoy?",
    searchButton: "buscar",
    apiParam: "es-ES",
    playButton: "Jugar",
    moreInfoButton: "Más información",
    signOutText: "desconectar",
    nowPlaying: "Corriendo ahora",
    upcoming: "Próximo",
    topRated: "Los más valorados",
    popular: "Popular",
    gptSearch: "Búsqueda de GPT",
    signIn: "Iniciar sesión",
    signUp: "Inscribirse",
    newToNetflix: "¿Nuevo en Netflix?",
    alreadyRegistered: "¿Ya registrado?",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    password: "Contraseña",
    suggestedMovies: "Películas sugeridas",
    searching: "Buscando...",
    goBack: "Volver",
  },
};

export default lang;
